---
fixtures:
  forge_modules:
    apt: "puppetlabs/apt"
    chocolatey: "puppetlabs/chocolatey"
    stdlib: "puppetlabs/stdlib"
    yumrepo_core: "puppetlabs/yumrepo_core"
  symlinks:
    fluentd: "#{source_dir}"
