fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.19.0"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "2.4.0"
  symlinks:
    fluentd: "#{source_dir}"
